import express from 'express';
import rateLimit from 'express-rate-limit';
import { authenticate } from '../middleware/auth.js';
import { User } from '../models/User.js';
import { RuntimeDevice } from '../models/RuntimeDevice.js';
import { hashRuntimeSecret } from '../services/runtime.service.js';
import { ApiError } from '../utils/ApiError.js';
import { asyncHandler } from '../utils/asyncHandler.js';
import { env } from '../config/env.js';
import * as c from '../controllers/runtime.controller.js';

export const runtimeRoutes = express.Router();
runtimeRoutes.use((_req, _res, next) => next(env.localRuntimeEnabled ? undefined : new ApiError(503, 'Local execution is disabled')));
const pairingLimit = rateLimit({ windowMs: 15 * 60_000, limit: 20, standardHeaders: true, legacyHeaders: false });
runtimeRoutes.post('/pairing', pairingLimit, c.pairing);
runtimeRoutes.post('/pairing/poll', rateLimit({ windowMs: 15 * 60_000, limit: 600, standardHeaders: true, legacyHeaders: false }), c.pairingPoll);
runtimeRoutes.post('/pairing/approve', pairingLimit, authenticate, c.approve);
const browserLimit = rateLimit({ windowMs: 60_000, limit: 60, standardHeaders: true, legacyHeaders: false });
const deviceId = (req, _res, next) => next(/^[a-f0-9]{24}$/i.test(req.params.id) ? undefined : ApiError.badRequest('Invalid computer ID'));
runtimeRoutes.get('/devices', browserLimit, authenticate, c.devices);
runtimeRoutes.post('/devices/:id/prefer', browserLimit, authenticate, deviceId, c.prefer);
runtimeRoutes.delete('/devices/:id', browserLimit, authenticate, deviceId, c.revoke);
runtimeRoutes.get('/download', browserLimit, authenticate, c.download);
runtimeRoutes.use(rateLimit({ windowMs: 60_000, limit: 1200, standardHeaders: true, legacyHeaders: false }));
runtimeRoutes.use(asyncHandler(async (req, _res, next) => {
  const token = req.headers.authorization?.replace(/^Bearer /, '');
  if (!/^[a-f0-9]{64}$/.test(String(token))) throw ApiError.unauthorized('Runtime authentication required');
  const device = await RuntimeDevice.findOne({ tokenHash: hashRuntimeSecret(token), revokedAt: null, expiresAt: { $gt: new Date() } });
  if (!device) throw ApiError.unauthorized('Runtime expired or revoked. Connect it again in Settings.');
  const user = await User.findOne({ _id: device.user, isActive: true });
  if (!user) throw ApiError.unauthorized('Account is unavailable');
  req.runtimeDevice = device; req.user = user; next();
}));
runtimeRoutes.use(rateLimit({ windowMs: 15 * 60_000, limit: 2400, keyGenerator: (req) => String(req.runtimeDevice._id), standardHeaders: true, legacyHeaders: false }));
runtimeRoutes.post('/heartbeat', c.heartbeat);
runtimeRoutes.post('/jobs/claim', c.claim);
runtimeRoutes.post('/jobs/:jobId/events', c.events);
runtimeRoutes.post('/jobs/:jobId/artifacts/:kind', express.raw({ type: 'application/octet-stream', limit: '32mb' }), c.artifact);
runtimeRoutes.get('/dataset/:name', c.dataset);
runtimeRoutes.post('/openai/v1/chat/completions', rateLimit({ windowMs: 60_000, limit: 40, keyGenerator: (req) => String(req.runtimeDevice._id), standardHeaders: true, legacyHeaders: false }), c.completion);
